### PR TITLE
Notes: Link directly to PDFs to avoid 404 errors

### PR DESCRIPTION
**Pull request by sglavoie**

### CODE REVIEW

**Comment by sglavoie** [comment]
@all-contributors please add @felipebalbi for review

**Comment by sglavoie** [comment]
@all-contributors please add @amenat  for bug, a11y, question

**Comment by sglavoie** [comment]
@all-contributors please add @Sukhjit-Mann for bug

**Comment by sglavoie** [comment]
@all-contributors please add @sglavoie for maintenance

**Comment by sglavoie** [comment]
Forgot that one:wink:.

@all-contributors please add @amenat for review

**Comment by sglavoie** [comment]
And that one... Would be great to do all those in one step, but anyways.

@all-contributors please add @sglavoie for review

**Comment by sglavoie** [comment]
@all-contributors please add @sglavoie for review

This is from a test to modify the bot's config. This is to trigger a new PR to sort things out (literally -> alphabetically :grin:).

**Comment by sglavoie** [comment]
@all-contributors please add @SergiusGit for doc

**Comment by sglavoie** [comment]
@all-contributors please add @SergiusGit for question

You've answered a bunch already. :smile:

**Comment by sglavoie** [comment]
@all-contributors please add @hitfzyangdianshi for doc

**Comment by sglavoie** [comment]
@all-contributors please add @gnufs for content

**Comment by sglavoie** [comment]
@all-contributors please add @tonihe for content

**Comment by ankush** [comment]
@all-contributors please add @tonihe for content, doc

**Comment by ankush** [comment]
copy paste got me

**Pull request merged**
