### PR TITLE
Add step to escalate a support issue to a complaint

### PR DESCRIPTION
**Pull request by mohanGups**
This pull request is about:

* [ ] Fixing a bug.
* [x] Updating documentation.
* [ ] Changing some functionality.
* [ ] Other (please explain).

I suggest adding the stage 2 student complaint procedure to the "Contacting UoL" page, as an escalation step where students have failed to receive a reasonable support. 

This is in response to one student asking on Slack what they should do if UoL deferred their final exam for their final project without informing them, and they have already waited for months for a response.

### CODE REVIEW

**Comment by mohanGups** [comment]
@sglavoie, can you please review or suggest another maintainer? Ta

**Review by sglavoie — APPROVED** [review]
Great, thank you! That information should definitely be available to those who need it. Hopefully they can find it easily enough.

**Comment by sglavoie** [comment]
@all-contributors please add @mohanGups for doc

**Comment by sglavoie** [comment]
@all-contributors please add @mohanGups for doc

**Pull request merged**
