### PR TITLE
Restructure level 6 modules and add module descriptions

### PR DESCRIPTION
**Pull request by eicksl**

### CODE REVIEW

**Comment by eicksl** [comment]
@sglavoie Hmm, what happened here? I see in the commit log that the branch was merged and can see that the changes were indeed added, but the PR is still open and showing merge conflicts. Do you want me to simply close this?

**Comment by sglavoie** [comment]
@eicksl Don't worry, I messed up :-1: . I will remerge your changes in a moment!

**Comment by sglavoie** [comment]
Thank you for your changes!

**Comment by sglavoie** [comment]
@all-contributors please add @eicksl for doc

**Pull request merged**
