### PR TITLE
Add sample steps to register RPL

### PR DESCRIPTION
**Pull request by renamoo**
### Description of the Change
I spent some time to complete RPL application as I was not sure what kind of systematic process I needed to take. Currently linked material is useful to understand the RPL details but it does not refer to the actual steps to follow so I'd like to supplement those information.

### CODE REVIEW

**Review by sglavoie — COMMENTED** [review]
Thank you for sharing these steps 🙂. I'll make some minor changes before merging because this repository is public while the linked screenshots are private and only accessible to currently enrolled students, which might be confusing for soon-to-be students.

**Comment by renamoo** [comment]
Thank you Sebastien for your review and fixes :)

**Comment by sglavoie** [comment]
@renamoo could you please link to this file from a publicly accessible link? -> https://londoncs.slack.com/files/U02FR0WJF99/F032CAMNMCG/screenshot-sits.london.ac.uk-2022.02.04-18_34_22.png

It looks like it might be from a private channel as I cannot open that link. If you'd like, you can always drag and drop the image here on GitHub when replying and we can move it elsewhere from that point. 🙂

**Comment by renamoo** [comment]
[@sglavoie](https://github.com/sglavoie) I don't have a good option in my mind for hosting so let me share the file here 🙇 
screenshot-sits london ac uk-2022 02 04-18_34_22

**Comment by sglavoie** [comment]
No worries, thank you for sharing the screenshots! There are no clearcut answers regarding the hosting: so far, we've been using another GitHub repository to host these types of binary files. -> https://github.com/world-class/binary-assets/tree/master/images/faq

All good to go now, thank you very much once again for making this degree a little bit easier to navigate. 😄

**Comment by sglavoie** [comment]
@all-contributors please add @renamoo for doc

**Pull request merged**
