### PR TITLE
Added links to Slack channels

### PR DESCRIPTION
**Pull request by irfanullahjan**
I've simply added links to slack channels for the modules.

### CODE REVIEW

**Review by ankush — APPROVED** [review]

**Comment by ankush** [comment]
I just noticed these are all "shared" links that prompt for installing the desktop app first :hidethepain:

Better to use `/client/` links that go straight to the page in the browser.

**Comment by irfanullahjan** [comment]
> I just noticed these are all "shared" links that prompt for installing the desktop app first :hidethepain:
> 
> Better to use `/client/` links that go straight to the page in the browser.

Not sure how to do that 😄. I tried payling with `slack://channel?id=xyz` but doesn't seem to work.

**Comment by ankush** [comment]
`https://app.slack.com/client/{team_id}/{channel_id}/`

**Comment by sglavoie** [comment]
Done! Thank you for pointing that out. It was indeed a bit annoying. :smile:

**Pull request merged**
