### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SoftOrbits**
👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.

1. Copy the correct template for your contribution from the below options.
2. Replace this text with the contents of the template
3. Fill in all sections of the template
4. Click "Create pull request"

## Bug Template

```
### Identify the Bug
<!--
Link to the issue describing the bug that you're fixing.

If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.
Note: In some cases, one person's "bug" is another person's "feature." If the pull request does not address an existing issue with the "bug" label, the maintainers have the final say on whether the current behavior is a bug.
-->

### Description of the Change
<!--
We must be able to understand the design of your change from this description. If we can't get a good idea of what the code will be doing from the description here, the pull request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the code here recently, so please walk us through the concepts.
-->

```

## Updating Documentation Template

```
### Description of the Change
<!--
We must be able to understand the purpose of your change from this description. If we can't get a good idea of the benefits of the change from the description here, the pull request may be closed at the maintainers' discretion.
-->

```

## Changing Functionality Template

```
<!--
### Requirements for Adding, Changing, or Removing a Feature

To contribute an enhancement, please follow our guide for suggesting an enhancement: https://github.com/world-class/REPL/blob/master/CONTRIBUTING.md#suggesting-enhancements
-->

### Description of the Change

<!--

We must be able to understand the design of your change from this description. If we can't get a good idea of what the contribution will be doing from the description here, the pull request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the code here recently, so please walk us through the concepts.

-->

<!-- The following sections are optional. -->

### Alternate Designs

<!-- Explain what other alternates were considered and why the proposed version was selected -->

### Possible Drawbacks

<!-- What are the possible side-effects or negative impacts of the code change? -->

```

### CODE REVIEW

**Comment by amenat** [comment]
If you're a student, please send PR from account that uses your real name and not organization's name.

**Comment by SoftOrbits** [comment]
Will do this from my personal account a bit letter. Appreciate if you accept this request

**Comment by amenat** [comment]
If you're UoL student and this is your project you can use "showcase" section instead. https://github.com/world-class/REPL/tree/master/showcase

**Comment by sglavoie** [comment]
Thank you @amenat for the heads up.

@SoftOrbits, this looks like spam and/or self-promotion to me. A :star: icon is used in the REPL for open source software. Your "offer" with the "Buy Now" button doesn't look like it qualifies.

**Pull request closed without merging**
